apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - 'infra/k8s/*.yaml'
build:
  local:
    push: false
  # googleCloudBuild:
  # projectId: ticketapp-dev-293320
  artifacts:
    # - image: us.gcr.io/ticketapp-dev-293320/auth
    - image: imjoshellis/tickets-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imjoshellis/tickets-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imjoshellis/tickets-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: imjoshellis/tickets-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
