name: deploy-client
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t imjoshellis/tickets-client .
      - run: docker login -u $DHU -p $DHP
        env:
          DHU: ${{ secrets.DH_USER }}
          DHP: ${{ secrets.DH_PASS }}
      - run: docker push imjoshellis/tickets-client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketapp
      - run: kubectl rollout restart deployment client-depl
